# /etc/salt/cloud.providers.d/incus.sdb.conf

incus-remote-sdb:
  driver: incus
  connection:
    type: https
    url: https://incus.example.com:8443
    cert_storage:
      type: sdb
      cert: sdb://vault/incus/client_cert
      key: sdb://vault/incus/client_key
      verify: sdb://vault/incus/ca_cert
