# /etc/salt/cloud.profiles.d/incus.local-files.conf

ubuntu-container-local:
  provider: incus-remote-local
  image: ubuntu/22.04
  type: container

ubuntu-vm-local:
  provider: incus-remote-local
  image: ubuntu/22.04
  type: virtual-machine
