# /etc/salt/cloud.providers.d/incus.local-files.conf

incus-remote-local:
  driver: incus
  connection:
    type: https
    url: https://incus.example.com:8443
    cert_storage:
      type: local_files
      cert: /etc/salt/pki/incus/client.crt
      key: /etc/salt/pki/incus/client.key
      verify: true
