# /etc/salt/cloud.profiles.d/incus.sdb.conf

ubuntu-container-sdb:
  provider: incus-remote-sdb
  image: ubuntu/22.04
  type: container

ubuntu-vm-sdb:
  provider: incus-remote-sdb
  image: ubuntu/22.04
  type: virtual-machine
